# Generated by Django 4.0.4 on 2022-05-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vol', models.PositiveIntegerField()),
                ('chap', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('add_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-vol', '-chap'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True)),
                ('manga_pic', models.ImageField(blank=True, default='manga_pics/no-image.jpg', upload_to='manga_pics/')),
                ('desc', models.TextField()),
                ('status', models.PositiveIntegerField(choices=[(0, 'Продолжается'), (1, 'Завершён'), (2, 'Заморожен'), (3, 'Заброшен')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.ImageField(upload_to='pages/')),
                ('queue', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['queue'],
            },
        ),
    ]
