# Generated by Django 4.0.4 on 2022-05-26 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('vol', 'chap', 'team')},
        ),
    ]
