# Generated by Django 4.0.4 on 2022-05-26 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_alter_profile_options_alter_chapter_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('vol', 'chap', 'manga', 'team')},
        ),
    ]
